---
linters:
  disable-all: true
  enable:
    - dogsled
    - gocritic
    - gofmt
    - govet
    - staticcheck
    - unused
    - whitespace

linters-settings:
  staticcheck:
    checks:
      - all
