---
linters:
  disable-all: true
  enable:
    - dogsled
    - gocritic
    - gofmt
    - staticcheck
    - whitespace

linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA1019'  # Disable rule SA1019
      - '-SA4017'  # Disable rule SA4017
