# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "tf-dev-box"

  config.vm.provider :libvirt do |lv|
    lv.cpu_mode = 'host-passthrough'
    lv.disk_bus = 'virtio'
    lv.driver = "kvm"
    lv.volume_cache = 'unsafe'
    lv.graphics_type = 'spice'
    lv.nic_model_type = 'virtio'
    lv.cpus = 2
    lv.memory = 1024

    lv.channel :type  => 'spicevmc', :target_name => 'com.redhat.spice.0',     :target_type => 'virtio'
    lv.channel :type  => 'unix',     :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
    lv.random  :model => 'random'
  end

  # Provision as vagrant user
  config.vm.provision "shell", path: "./tf-glesys-setup.sh", privileged: false

end
